name: Test scripts

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: fish-shop/install-fish-shell@v1.0.33
      - uses: fish-shop/indent-check@v1.0.20
      - uses: fish-shop/syntax-check@v2.2.21
      - uses: fish-shop/install-plugin@v2.3.23
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@v2.3.22
