name: Test scripts

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-fish:
    name: Check Fish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: block
          allow-sudo: false
          allowed-endpoints: >
            _http._tcp.azure.archive.ubuntu.com:443
            _https._tcp.esm.ubuntu.com:443
            _https._tcp.motd.ubuntu.com:443
            _https._tcp.packages.microsoft.com:443
            _https._tcp.ppa.launchpadcontent.net:443
            api.github.com:443
            api.launchpad.net:443
            azure.archive.ubuntu.com:80
            esm.ubuntu.com:443
            github.com:443
            motd.ubuntu.com:443
            packages.microsoft.com:443
            ppa.launchpadcontent.net:443
            raw.githubusercontent.com:443
            registry.npmjs.org:443

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: fish-shop/install-fish-shell@948417ca21b8789ef8954625db3035148e53ac74 # v2.1.29
      - uses: fish-shop/indent-check@f73ce7c50dcb1bd881d70b91dd7986db427dc063 # v2.2.120
      - uses: fish-shop/syntax-check@0fb845a43205c9b67827d8f7af0b6b7cfb59095d # v2.2.118
      - uses: fish-shop/install-plugin@450a337f4e2d613c2b8cf66bc0454801ea38d4c3 # v2.3.122
        with:
          plugin-manager: fisher
          plugins: IlanCosman/clownfish
      - uses: fish-shop/run-fishtape-tests@9f0e79359f472f05781a1eedd5c47013159db9de # v2.3.122
